name: Deploy Website - CI (GitHub Pages)

on:
  push:
    branches: [ "**" ]
    paths: [ 'portfolio/**' ] 
  pull_request:
    branches: [ "**" ]
    paths: [ 'portfolio/**' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./portfolio 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: './portfolio/package-lock.json' 

      - name: Install Dependencies
        run: npm ci

      - name: Build Site (Check for compile errors)
        run: npm run build
